import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("resultados.csv")
df_b = df[df["arbol"] == "B"]
df_bp = df[df["arbol"] == "B+"]

# BTree
plt.plot(df_b["N"], df_b["t_creacion_ms"], marker="o")
plt.xscale("log", base=2)
plt.xlabel("N (claves)")
plt.ylabel("Tiempo (ms)")
plt.title("Tiempo de construcción Árbol B")
plt.grid(True)
plt.savefig("img/Resultados/B_construccion.png")
plt.clf()

plt.plot(df_b["N"], df_b["io_crea_esc"], marker="o", label="Escrituras")
plt.plot(df_b["N"], df_b["io_crea_lec"], marker="o", label="Lecturas")
plt.xscale("log", base=2)
plt.xlabel("N (claves)")
plt.ylabel("Operaciones I/O")
plt.title("I/O simuladas en construcción Árbol B")
plt.legend()
plt.grid(True)
plt.savefig("img/Resultados/B_ios.png")
plt.clf()

plt.plot(df_b["N"], df_b["t_busq_ms_prom"], marker="o")
plt.xscale("log", base=2)
plt.xlabel("N (claves)")
plt.ylabel("Tiempo (ms)")
plt.title("Tiempo promedio de consulta Árbol B")
plt.grid(True)
plt.savefig("img/Resultados/B_busqueda.png")
plt.clf()

# BPlus Tree
plt.plot(df_bp["N"], df_bp["t_creacion_ms"], marker="o")
plt.xscale("log", base=2)
plt.xlabel("N (claves)")
plt.ylabel("Tiempo (ms)")
plt.title("Tiempo de construcción Árbol B+")
plt.grid(True)
plt.savefig("img/Resultados/Bplus_construccion.png")
plt.clf()

plt.plot(df_bp["N"], df_bp["io_crea_esc"], marker="o", label="Escrituras")
plt.plot(df_bp["N"], df_bp["io_crea_lec"], marker="o", label="Lecturas")
plt.xscale("log", base=2)
plt.xlabel("N (claves)")
plt.ylabel("Operaciones I/O")
plt.title("I/O simuladas en construcción Árbol B+")
plt.legend()
plt.grid(True)
plt.savefig("img/Resultados/Bplus_ios.png")
plt.clf()

plt.plot(df_bp["N"], df_bp["t_busq_ms_prom"], marker="o")
plt.xscale("log", base=2)
plt.xlabel("N (claves)")
plt.ylabel("Tiempo (ms)")
plt.title("Tiempo promedio de consulta Árbol B+")
plt.grid(True)
plt.savefig("img/Resultados/Bplus_busqueda.png")
plt.clf()

# Comparacion entre ambos
plt.plot(df_b["N"], df_b["t_creacion_ms"], marker="o", label="B")
plt.plot(df_bp["N"], df_bp["t_creacion_ms"], marker="o", label="B+")
plt.xscale("log", base=2)
plt.xlabel("N (claves)")
plt.ylabel("Tiempo (ms)")
plt.title("Comparación de tiempos de construcción")
plt.legend()
plt.grid(True)
plt.savefig("img/Resultados/comparacion_construccion.png")
plt.clf()

plt.plot(df_b["N"], df_b["t_busq_ms_prom"], marker="o", label="B")
plt.plot(df_bp["N"], df_bp["t_busq_ms_prom"], marker="o", label="B+")
plt.xscale("log", base=2)
plt.xlabel("N (claves)")
plt.ylabel("Tiempo promedio consulta (ms)")
plt.title("Comparación tiempos de consulta")
plt.legend()
plt.grid(True)
plt.savefig("img/Resultados/comparacion_busqueda.png")
plt.clf()

plt.plot(df_b["N"], df_b["io_crea_esc"], marker="o", label="B escrituras")
plt.plot(df_bp["N"], df_bp["io_crea_esc"], marker="o", label="B+ escrituras")
plt.xscale("log", base=2)
plt.xlabel("N (claves)")
plt.ylabel("Operaciones de escritura")
plt.title("Comparación I/O simuladas en construcción")
plt.legend()
plt.grid(True)
plt.savefig("img/Resultados/comparacion_ios.png")
plt.clf()